import Footer from '@/ui/Footer'

import '../styles/globals.scss'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const neueHaas = localFont({
  variable: '--font-neue-haas',
  display: 'swap',
  src: [
    {
      path: '../fonts/nhgd/NeueHaasDisplay-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/nhgd/NeueHaasDisplay-Roman.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/nhgd/NeueHaasDisplay-Mediu.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/nhgd/NeueHaasDisplay-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={neueHaas.variable}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
